name: bazaar

services:
  bazaar-front:
    build: .
    container_name: bazaar-front
    environment:
      - FRONT_EXTERNAL_PORT=${FRONT_EXTERNAL_PORT}
    env_file:
      - ".env"
    ports:
      - "$FRONT_EXTERNAL_PORT:80"
    restart: unless-stopped
    networks:
      - bazaar-net
    depends_on:
      bazaar-back:
        restart: true
        condition: service_started
    links:
      - "bazaar-back:backend"
    healthcheck:
      test: curl -f http://localhost:8090/api/users/me/ || exit 1
      retries: 3
      interval: 3s
      timeout: 10s
  bazaar-back:
    image: niknike/bazaar
    container_name: bazaar-back
    hostname: bazaar-back
    restart: unless-stopped
    networks:
      - bazaar-net
    environment:
      - ALLOW_ORIGIN=${ALLOW_ORIGIN}
    ports:
      - "8090:8080"

networks:
  bazaar-net:
    driver: bridge

